apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test-ns
  labels:
    app.kubernetes.io/name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test-ns
  labels:
    app.kubernetes.io/name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0.15
          livenessProbe:
            tcpSocket:
              port: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
          startupProbe:
            tcpSocket:
              port: 3306
            failureThreshold: 10
            periodSeconds: 10
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: test-ns
  labels:
    app.kubernetes.io/name: redis
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: test-ns
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: redis
          image: redis:4-alpine
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 10
            periodSeconds: 10
          ports:
            - containerPort: 6379
